---
title: "Mini-Project 3"
author: "Eleanor Ewing, G.E. Ranieri, Farah Samawi"
date: "11/15/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mdsr)
library(RMySQL)
```

```{r}
db <- dbConnect_scidb(dbname = "imdb")
```

```{r}
query <- "SELECT movie_id, 
	               COUNT(CASE WHEN info_type_id = 3 THEN info ELSE NULL END) AS genres,
	               production_year
          FROM imdb.movie_info
          LEFT JOIN title ON movie_info.movie_id = title.id
          WHERE kind_id = 1 AND 
	              production_year IS NOT NULL AND 
	              info IS NOT NULL AND 
	              movie_id IN (SELECT movie_id
				                     FROM movie_info
				                     WHERE info_type_id = 8 AND info LIKE '%USA%')
          GROUP BY movie_id;"

query_data <- db %>%
  dbGetQuery(query)
```

```{r}
# Make scatter plot
gplot <- ggplot(query_data, aes(x = production_year, y = genres)) +
  geom_jitter(alpha = 0.1) +
  geom_vline(xintercept = 1947, color = "red")

gplot
```
